name: Integration test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-test:
    # default smoke test against python-3.10 on ubuntu-latest
    uses: ./.github/workflows/integration_test_workflow.yml

  integration-test:
    needs: pre-test
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/integration_test_workflow.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
