name: Integration test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# If another push to the same PR or branch happens while this workflow is still running,
# cancel the earlier run in favor of the next run.
#
# There's no point in testing an outdated version of the code. GitHub only allows
# a limited number of job runners to be active at the same time, so it's better to cancel
# pointless jobs early so that more useful jobs can run sooner.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-test:
    uses: ./.github/workflows/integration_test_workflow.yml

  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    uses: ./.github/workflows/integration_test_workflow.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
